### ISSUE TITLE
Runtime.consoleAPICalled() doesn't seem to work

### ISSUE THREAD

**Issue by pthieu** [cyrus-and/chrome-remote-interface#109]
Testing out code, not getting anything back from this:
```
Runtime.consoleAPICalled(() => {
  console.log(arguments);
});

Runtime.evaluate({
  expression: `(${function(){
    console.log('test console api call');
  }})()`,
  awaitPromise: true,
});
```

Also tried to use the `Log.entryAdded` event, but didn't detect my `console.log`'s. I just want to print some data into client console and be able to see that in my terminal.

**Comment by cyrus-and** [comment]
There some issues with that code:

1. `arguments` doesn't work with arrow functions, meaning that you'll get the `arguments` of a parent regular function or `undefined`.

2. your expression doesn't return a Promise so you cannot use `awaitPromise: true`;

3. finally events are not delivered because you need to enable the `Runtime` domain first:

        Runtime.enable();

**Comment by pthieu** [comment]
@cyrus-and: thanks. I missed the part in the documentation for `#3` and didn't know about `#1`. For `#2`, I simplified the code for the issue, my original code had a promise returned.

Do you know if any of the `.enable()` methods just allow for events to trigger? Seems like we can use other methods in each of the domain without first enabling. At least I'm able to do a `Runtime.evaluate()` without first doing `Runtime.enable()`.

**Comment by cyrus-and** [comment]
> Do you know if any of the .enable() methods just allow for events to trigger?

AFAIK it's not documented anywhere but the rule of thumb is that in order to receive events from a given domain you need to enable it first. There a few exceptions though, sometimes you need to enable a domain in order to use its methods, see the [follow-up question] in #102.

[follow-up question]: https://github.com/cyrus-and/chrome-remote-interface/issues/102#issuecomment-294949036
