### ISSUE TITLE
Question: How to pass messages to a Chrome extension?

### ISSUE THREAD

**Issue by paambaati** [cyrus-and/chrome-remote-interface#119]
I have a Chrome extension with the `debugger` permissions on, and I'm trying to use this module to try to pass messages to it.

I tried this -

```js
function sendMessageToExtension(extensionID) {
        return CDP.List((err, targets) => {
            let target = targets.filter(target => target.url.startsWith('chrome-extension://'))
            target = target && target[0];
            if (!target) {
                throw new Error('No extensions were loaded!');
            }
            return CDP({tab: 'ws://localhost:9222/devtools/browser'}, client => {
                const { Target } = client;
                return Target.createTarget({url: 'ws://localhost:9222/devtools/browser'}, target => {
                    return Target.sendMessageToTarget({ targetId: target.id, message: 'xxx' }).then(x => {
                            console.log('final = ', x);
                            return x;
                        });
                });
            });
        });
    }
```

I also tried this - 

```js
function sendMessageToExtension(extensionID) {
        return CDP.List((err, targets) => {
            let target = targets.filter(target => target.url.startsWith('chrome-extension://'))
            target = target && target[0];
            if (!target) {
                throw new Error('No extensions were loaded!');
            }
            return CDP({tab: 'ws://localhost:9222/devtools/browser'}, client => {
                const { Target } = client;
                return Target.attachToTarget({ targetId: target.id }, done => {
                    console.log('ATTACH? ', done);
                    return Target.activateTarget({ targetId: target.id }, done => {
                        console.log('ACTIVATE? ', done);
                        return Target.sendMessageToTarget({ targetId: target.id, message: 'xxx' }).then(x => {
                            console.log('final = ', x);
                            return x;
                        });
                    });
                });
            });
        });
    }
```

Both functions throw a `'Target.sendMessageToTarget' wasn't found` error. I've tried with the remote switch set to both possible values, and still no luck!

**Comment by cyrus-and** [comment]
So there are several points to be addressed here.

You get `'Target.sendMessageToTarget' wasn't found` probably because your Chrome version is too old to support that method which is hard coded in the bundled `protocol.json`. What version are you using?

But anyway I don't think the `Target` domain is what you want, because:

- `Target.createTarget` actually creates a tab and you don't need to create the `ws://localhost:9222/devtools/browser` target as it's already there even if it doesn't appear in the list;

- `Target.attachToTarget` allows you to use the `Target.sendMessageToTarget` on a target, but here the `message` field is expected to be a Chrome Debugging Protocol JSON message, i.e., `{"id": ..., "method": ..., "params": {...}}`, which is exactly what this module does natively.

So you probably should just attach to your extension and use the protocol API to interact with it but please note that you cannot access the Chrome extension API directly from here, you may attempt to inject some code with `Runtime.evaluate` but I've never tried.

What I mean is something like this:

```js
CDP({
    target: targets => targets.find(target => target.url.startsWith('chrome-extension://'))
}, client => {
    // ...
});
```
