### ISSUE TITLE
Can someone give a Browser usage example of function criRequest ?

### ISSUE THREAD

**Issue by Mazza-Chen** [cyrus-and/chrome-remote-interface#122]
Hi,  I  want to use chrome-remote-interface(cri) in browser,
I have been successfully webpacked cri into a bundled file,
[Here mentioned:](https://github.com/cyrus-and/chrome-remote-interface/#using-vanilla-javascript)
 `function criRequest(options, callback)`
Can anyone give a more detailed example of this function?
I mean that some example can do things like below:
`client.Page.navigate({'url': 'https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-navigate'}, console.log);`
Thank you!

**Comment by cyrus-and** [comment]
You need your own backend, to which your web application can communicate without violating the SOP. That's needed because the HTTP endpoint of Chrome (e.g., `/json/list`) doesn't reply with an `Access-Control-Allow-Origin` header that enables your web application to perform requests towards it.

Your own backend would be basically a proxy which performs requests to the HTTP endpoint of Chrome on the behalf of your web application.

See a real world example [here][1] where `networkRequest` is defined [here][2].

[1]: https://github.com/devtools-html/devtools-core/blob/9881990dd1e37c0ede527e2e88979a3c1c110037/packages/devtools-launchpad/src/client/chrome.js#L32-L39

[2]: https://github.com/devtools-html/devtools-core/blob/8dd96c9deb46915f50933f5e40ad6a4cf7b2c6d7/packages/devtools-utils/src/network-request.js#L6-L19

**Comment by Mazza-Chen** [comment]
So great having your advice, I will delve into it. Thank you~
