### ISSUE TITLE
Change `Async await example` to embrace async\await?

### ISSUE THREAD

**Issue by cowchimp** [cyrus-and/chrome-remote-interface#146]
Hi. Thanks for Chrome Remote Interface!
It's been a great help.

One question about
https://github.com/cyrus-and/chrome-remote-interface/wiki/Async-await-example

The point of this example is to embrace promises and async\await.
Wanted to ask if in this case it should be re-written as:

```javascript
CDP().then(client => {
  const {Network, Page} = client;
  //...
}, err => {
  console.error('Cannot connect to browser:', err);
});
```
Thanks!

**Comment by cyrus-and** [comment]
Glad to hear that! :)

Well, not exactly, the main example already uses `Promises` the point of this wiki example was to show how to avoid `then`/`catch` in favour of `async`/`await`.

I didn't use `then`/`catch` in the main example because I find it less clear to catch connection errors (for the sake of the example).

If anything, I'd rewrite that wiki example using `async`/`await` for everything but I'd need to wrap it in an `async` function, which is kind of ugly, but really shows the full potential:

```js
const CDP = require('chrome-remote-interface');

async function example() {
    try {
        // connect to endpoint
        var client = await CDP();
        // extract domains
        const {Network, Page} = client;
        // setup handlers
        Network.requestWillBeSent((params) => {
            console.log(params.request.url);
        });
        // enable events then start!
        await Promise.all([Network.enable(), Page.enable()]);
        await Page.navigate({url: 'https://github.com'});
        await Page.loadEventFired();
    } catch (err) {
        console.error(err);
    } finally {
        if (client) {
            await client.close();
        }
    }
}

example();
```

What do you think?

**Comment by cowchimp** [comment]
Yes, exactly. This is much neater IMHO.
Also, I wouldn't worry too much about the "ugly" wrapping function. Anyone who is familiar with asynchronous/await will be familiar with why it's required and won't judge.

**Comment by cyrus-and** [comment]
Alright then, I updated the wiki. Thanks for pointing this out.
