### ISSUE TITLE
 Error: 'Network.enable' wasn't found

### ISSUE THREAD

**Issue by liangtongxie** [cyrus-and/chrome-remote-interface#156]
![asfa](https://user-images.githubusercontent.com/16974453/26919898-d374b018-4c69-11e7-9d3c-7b49747ac3ba.jpg)
![sdfasf](https://user-images.githubusercontent.com/16974453/26919975-18271624-4c6a-11e7-804b-09b28bd9ce62.png)

I have done followed by the example on the document , but the error occurs , anyone help me ?

os : window7

node : 6.10.1

**Comment by cyrus-and** [comment]
That's because Node.js exposes a different protocol (with respect to Chrome) and as you can [see][1] there is no `Network` domain there. You can inspect just the V8 runtime of Node.js.

I think you want to use the above script with a Chrome instance not with a Node.js instance.

[1]: https://chromedevtools.github.io/debugger-protocol-viewer/v8/

**Comment by liangtongxie** [comment]
@cyrus-and,  thank you.
