### ISSUE TITLE
How can I run an xpath expression?

### ISSUE THREAD

**Issue by fracasula** [cyrus-and/chrome-remote-interface#165]
Hi everyone,

I checked the docs [here](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/) but it's not clear to me whether there's a way to make the class `Runtime` evaluate not just JavaScript expressions but also XPaths.

Has anyone tried?

**Comment by cyrus-and** [comment]
I think what you want is [`DOM.performSearch`][1]:

[1]: https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-performSearch

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    try {
        // extract and enable domains
        const {DOM, Page} = client;
        await DOM.enable();
        await Page.enable();
        // navigate the page
        await Page.navigate({url: 'http://example.com'});
        await Page.loadEventFired();
        // "It is important that client receives DOM events only for the nodes
        // that are known to the client."
        await DOM.getDocument();
        // perform the XPath search query
        const {searchId, resultCount} = await DOM.performSearch({
            query: '/html/body/div/*'
        });
        // fetch and display all the results
        const {nodeIds} = await DOM.getSearchResults({
            searchId,
            fromIndex: 0,
            toIndex: resultCount
        });
        console.log(nodeIds);
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

Otherwise you can always use [`Runtime.evaluate`][2] to inject a [`Document.evaluate`][3] call.

[2]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate
[3]: https://developer.mozilla.org/en/docs/Web/API/Document/evaluate

**Comment by kensoh** [comment]
Thanks Andrea @cyrus-and for creating chrome-remote-interface project and sharing with the community! I saw that Chromy project is also recently built on top of this project.

I was thinking to use chrome-remote-interface initially for my [web automation project](https://github.com/tebelorg/TagUI/issues/24) but ended up integrating directly to Chrome in order to avoid Node.js dependency for non-dev users.

@fracasula adding on, I'm using document.evaluate call Andrea mentioned - 
Checking this to see if > 0 to check existence of element
```
document.evaluate(XPATH_SELECTOR,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength
```

Using this to get the first element that matches and do stuff
```
document.evaluate(XPATH_SELECTOR,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0)
```

**Comment by tsirolnik** [comment]
I would like to note that WITHOUT calling `DOM.getDocument` prior to performing the search results, the output of `getSearchResults` will be an array with zeros.

Code:

```js  
        // Removing this line will cause getSearchResults to return an array filled with zeros.
         await DOM.getDocument();
        let { searchId, resultCount } = await DOM.performSearch({ query: xpath });
        if (resultCount < 1) return null;
        let { nodeIds } = await tDOM.getSearchResults({
            searchId,
            fromIndex: 0,
            toIndex: resultCount
        });
        console.log(nodeIds);
        nodeIds.forEach(async id => {
            // This will fail without DOM.getDocument
            console.log(await DOM.getAttributes({ nodeId: id })); 
        })
```

**Comment by motyar** [comment]
@tsirolnik How we can get innerHTML? or text

**Comment by cyrus-and** [comment]
@motyar [DOM.getOuterHTML][1] may be a possibility.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getOuterHTML

**Comment by motyar** [comment]
I am trying to change this to fetch by *xpath*, current code works with CSS selectors.
https://github.com/t9tio/cloudquery/blob/master/app.js#L132
