### ISSUE TITLE
cdp freezes/hangs with no output

### ISSUE THREAD

**Issue by JakobLofgren** [cyrus-and/chrome-remote-interface#174]
# Console output:

spawned chrome task
spawned cdp
enabled page
navigated
page loaded

# Code:

Gist [here](https://gist.github.com/JakobLofgren/689c2f58f18932d4afb00b417dc4155c)

# Desciption of problem:

The "task" just hangs/freezes and doesnt give any output. Preferbly, you would also teach me how I enable logging so I can deal with any further issues. aswell as pointing out what I did wrong 😄

**Comment by cyrus-and** [comment]
A Chrome instance exposes a number of targets which are not necessarily just tabs, for example there are service workers, background pages of extensions, etc. by default this module hooks to the first available target. Usually Chrome keeps this list (`CDP.List()`) ordered by usage frequency (most recently used first).

Now the `chrome-launcher` module doesn't work for me, but in my case (an probably yours) the *first* target is the background page of the `CryptoTokenExtension`. So apart from explicitly create a new tab for your purpose a possible solution might be to filter the targets and attach to proper pages only:

```js
const target = (targets) => {
    return targets.find(target => target.type === 'page');
};

const client = await CDP({ port, target })
```

> Preferbly, you would also teach me how I enable logging so I can deal with any further issues.

I'm afraid there's no such thing for what concerns this module, but in this case it helped to take a look at the available targets with `chrome-remote-interface list`.

Hope it help!

---

PS this won't work because `close()` is a proper method of the CDP class and you'll lose the reference to `this`:

```js
const {close} = client();
close();
```

**Comment by cyrus-and** [comment]
FYI the default behavior is now to prefer `type === 'page'` targets (014e3f06ec63ab39c3439f1727a7c431a0ef9223).

**Comment by JakobLofgren** [comment]
Silly me, apparently Windows doesn't get headless support until Chrome v60. I was using v59 😮 . I will get back to you once I can update to v60 if this is still an issue
