### ISSUE TITLE
Expose  `object.error.data` in case of error.

### ISSUE THREAD

**Issue by paulirish** [cyrus-and/chrome-remote-interface#185]
I'm not totally familiar with CRI's error handling so maybe this isn't needed.

But FYI the `error.data` string sometimes has valuable data that should be surfaced to the user.
https://github.com/GoogleChrome/lighthouse/pull/2645

**Comment by cyrus-and** [comment]
I'm returning a [`ProtocolError`][1] to the user like this:

```js
class ProtocolError extends Error {
    constructor(response) {
        super(response.message);
        Object.assign(this, response);
    }
}
```

`message` is used as the actual error message while `code` and `data` (if any) are additional properties. This seemed to me the best option since AFAIK the response format is not documented.

Thanks for the info! :)

[1]: https://github.com/cyrus-and/chrome-remote-interface/blob/9638de9b15a097904bad8418124d7837b03a1210/lib/chrome.js#L12-L17

**Comment by paulirish** [comment]
gotcha. 

![image](https://user-images.githubusercontent.com/39191/27938609-f919967e-6273-11e7-868d-1ac03fb7167f.png)

While I think the cri CLI is mostly unaffected anyone using it as a module will typically only see message, as `.data` is very atypical for an error object.

I would probably suggest this, then. The benefit is you are sure any useful information provided in `data` is definitely shown to the user.

```js
class ProtocolError extends Error {
    constructor(response) {
        super(`${response.message} (${response.data})`);
        Object.assign(this, response);
    }
}
```

**Comment by cyrus-and** [comment]
I was somewhat reluctant to do something like this due to the apparent lack of coherence in the format of those strings (capitalization, punctuation, etc.), but I definitely see the value in this.

Added in b025371dcf056fcbc248c321abccbf5d380e4659.
