### ISSUE TITLE
Error: not opened // missing error handling?

### ISSUE THREAD

**Issue by s-thet** [cyrus-and/chrome-remote-interface#189]
Hi,

we used the chrome-remote-interface in test automization and had issues with restarting chrome. 

At some point there are messages to be sent through the websocket, although the socket is broken.

The whole node process then fails with `Error: not opened`.

We were able to fix the issue with adding error handling to the WebSocket.send call in the `enqueueCommand` function found in lib/chrome.js:

```
    chrome._ws.send(JSON.stringify(message),function(err) {
        if (err) return;
        chrome._callbacks[id] = callback;
    });
```

I was not yet able to reproduce the issue in a minimalistic setup.

I submitted a pull request, in case you like the change: https://github.com/cyrus-and/chrome-remote-interface/pull/188

**Comment by cyrus-and** [comment]
Thanks for pointing this out. Here's how to reproduce (even though this is a regular close):

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    try {
        await client.close();
        await client.Page.reload();
    } catch (err) {
        console.error(err);
    }
}).on('error', (err) => {
    console.error(err);
});
```

Now, if you use promises (which is BTW recommended) then this exception should be automatically caught, but it's just a consequence, I agree that this needs a fix.

(On a side note the `disconnect` event of `client` should trigger in the situation you describe.)

The problem with #188 (apart from failing integration tests due to formatting) is that it simply swallows the error, it would be nice if it were returned to the user for handling instead, just like any regular error.

e162819a453729c121b428b24243e28598d48547 allows the user to handle even such errors so that there are no unhandled exceptions and the Node.js process is not killed. Depending on your setup this should just work, if instead you're using callbacks, here's an example of the *full* program flow:

```js
client.Domain.Method(params, (error, params) => {
    if (error) {
        if (error instanceof Error) {
            console.error('WebSocket error:', error);
        } else {
            console.error('Protocol error:', params.error);
        }
    } else {
        console.log('OK:', params.result);
    }
});
```

JavaScript promises enable a much more elegant code.
