### ISSUE TITLE
How to wait for browser event?

### ISSUE THREAD

**Issue by klodoma** [cyrus-and/chrome-remote-interface#19]
Hi, 

This is a question not an issue, so if it's not the right place to post this, sorry. 
I'm trying out this piece of code, but I can't figure out how to "wait" for something from the browser. 

For example:
I want to go to a url, load a page and wait for something in the console or for an event. 
The url is opening, but the nodejs code is immediately closed(which makes sense). 

    Page.navigate({'url': 'http://mypage.com'});
    // how to wait? 

This is your sample code:

    var Chrome = require('chrome-remote-interface');
    Chrome(function (chrome) {
        with (chrome) {
            Network.requestWillBeSent(function (params) {
                console.log(params.request.url);
            });
            Page.loadEventFired(close);
            Network.enable();
            Page.enable();
            once('ready', function () {
                Page.navigate({'url': 'https://github.com'});
                //how to wait for a console message or event?
            });
        }
    }).on('error', function () {
        console.error('Cannot connect to Chrome');
    });

Thanks in advance!

**Comment by cyrus-and** [comment]
NodeJS closes once `chrome.close()` is called. In the above example this happens when the load event is fired by Chrome due to this line:

    Page.loadEventFired(close);

All you have to do is remove that line and call `chrome.close()` once your event is fired.

For example, say you want to exit once a certain word ("png") appears in a requested URL:

```javascript
Network.requestWillBeSent(function (params) {
    console.log(params.request.url);
    if (params.request.url.match(/png/)) {
        close();
    }
});
// Page.loadEventFired(close);
```

Another example, here the program exit 5 seconds after the page load event is fired:

```javascript
Page.loadEventFired(function () {
    setTimeout(function () {
        close();
    }, 5000);
});
```

If instead you just want to wait a specific time since the beginning:

```javascript
// Page.loadEventFired(close);
once('ready', function () {
    Page.navigate({'url': 'https://github.com'});
    setTimeout(function () {
        close();
    }, 5000);
});
```

I'm showing just the relevant bits, but it should be clear nonetheless. Otherwise please do not hesitate to ask.

**Comment by klodoma** [comment]
Thank you for your quick and comprehensive answer! I really missed this call:

    Page.loadEventFired(close);

**Comment by cyrus-and** [comment]
You're welcome!
