### ISSUE TITLE
How to resume Debugger when `--inspect-brk` ?

### ISSUE THREAD

**Issue by atian25** [cyrus-and/chrome-remote-interface#286]
```js
'use strict';

const CDP = require('chrome-remote-interface');
const cp = require('child_process');
const sleep = require('mz-modules/sleep');

async function fn() {
  let client;
  try {
    const child = cp.fork('./child', [], { execArgv: [ '--inspect-brk=9229' ] });
    await sleep('2s');
    console.log(child.connected && 'fork child');

    client = await CDP({ port: 9229 });

    const { Debugger } = client;
    console.log('attached');

    // pending at here
    await Debugger.enable();
    console.log('enabled');

    await Debugger.resume();
    console.log('resume');
  } catch (err) {
    console.error(err);
  } finally {
    console.log('close');
    if (client) {
      await client.close();
    }
  }
}

fn().catch(console.error);
```

child.js
```js
console.log(1);
console.log(2);
```

output:

```bash
➜  cdp-test node index.js
Debugger listening on ws://127.0.0.1:9229/d23439a7-9607-43f2-93f3-d47e09dcd436
For help see https://nodejs.org/en/docs/inspector
fork child
attached
```

| Component | Version
|-|-
| Operating system	  	 	| Mac
| Node.js					| v8.5.0
| chrome-remote-interface	| latest ^0.25.2

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
You need to issue [`Runtime.runIfWaitingForDebugger`][1] before enabling the `Debugger` domain (see this [wiki][2]):

```js
await Runtime.runIfWaitingForDebugger();
await Debugger.enable();
```

But after that you'll get `Error: Can only perform operation while paused` meaning that you should explicitly wait the debugger to be paused in order to resume it:

```js
await Debugger.paused();
await Debugger.resume();
```

Hope it helps. Unfortunately this part is a bit contrived and scarcely documented. I suggest you to inspect [DevTools][3] (see "Sniffing the protocol") to figure out how things are implemented.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-runIfWaitingForDebugger
[2]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Connect-to-Node.js
[3]: https://chromedevtools.github.io/devtools-protocol/

**Comment by atian25** [comment]
thanks
