### ISSUE TITLE
Issues when running over port 80 using `tab` params

### ISSUE THREAD

**Issue by joelgriffith** [cyrus-and/chrome-remote-interface#294]
| Operating system	  	 	| macOS 10.12.3
| Node.js					| v8.1.2
| Chrome/Chromium/...		| HeadlessChrome/64.0.3240.0
| chrome-remote-interface	| 0.25.2

Is Chrome running in a container? NO

I'm providing a web-service layer over Chrome that acts very similar as a proxy, but provides access to Chrome over port 80 and internally proxies traffic into Chrome via whatever port it's running on (which changes dynamically). Currently, I'm fetching the list of available targets manually since I there's query-string parameters as well, and there's no way of having qs params with the default interface (eg: `{ host: "hostname", port: "port" }`).

The code roughly look like:

```
return fetch('http://my-chrome-service.com')
  .then((res) => res.json())
  .then((targets) => {
    return CDP({
      tab: targets[0].webSocketDebuggerUrl
    });
  })
```

With targets looking like:
```
[ { targetId: '/devtools/page/(FFEA7FDD189C5E1585DE54556266AA10)',
    description: '',
    devtoolsFrontendUrl: '/devtools/inspector.html?ws=my-chrome-service.com/devtools/page/(FFEA7FDD189C5E1585DE54556266AA10)',
    title: 'about:blank',
    type: 'page',
    url: 'about:blank',
    webSocketDebuggerUrl: 'ws:/my-chrome-service.com/devtools/page/(FFEA7FDD189C5E1585DE54556266AA10)' } ]
```

Everything works fine until https://github.com/cyrus-and/chrome-remote-interface/blob/master/lib/chrome.js#L147. Since this app is on port 80, and it's not explicit in the URL, this call will return

```
Url {
  protocol: 'ws:',
  slashes: true,
  auth: null,
  host: 'chrome-service.com',
  port: null,
```

Since the `port` here is null, this will then cause downstream calls for `/json/protocol` and others to fail as it then defaults to `9222`. https://github.com/cyrus-and/chrome-remote-interface/blob/master/lib/devtools.js#L103 is the first culprit.

I can change things on my end to always append a port, however I'm curious what the sentiment here is about using chrome-remote-interface when it's referencing resources behind a web-service of some kind. Likely not something that was an initial use-case, but has been something I've been fighting on my end.

I'd be happy to do the work and submit a PR to try and tackle this, but wanted to get some buy-in from maintainers and get some perspective. Let me know if I can provide more context.

**Comment by cyrus-and** [comment]
The fact is that there is no general solution, for example PR #284 was (I think) a way to address a similar problem, as you can see this is yet another method (i.e., sub path vs query string).

In making this module ready for running into a [web context][1], I had to extract  the function that made the actual [external request][2] so that it could be replaced with the `fetch()` API and adjusted to properly talk with the backend. This *replacement* is performed by webpack, which admittedly, I know very little about. Do you think something similar can be accomplished to replace that function in a Node.js context?

Otherwise I don't think it would be to hard to add to the Node.js API. I just struggle to find an elegant way to do that since it would impact the `CDP.*` methods and `CDP()`. Maybe something like:

```js
const CDP = require('chrome-remote-interface');
CDP.externalRequest = myExternalRequest;
```

Besides, what would be your solution? I'm not sure if making the API more generic so to accept additional parameters such as query string would be advisable; I need to thoroughly think about the consequences. I'm more inclined to provide a way to provide a user-defined `externalRequest` function. But please let me know what you think.

[1]: https://github.com/cyrus-and/chrome-remote-interface#browser-usage
[2]: https://github.com/cyrus-and/chrome-remote-interface/blob/master/lib/external-request.js

**Comment by joelgriffith** [comment]
I think in the short term I can always return a `port` in the `/json/list` call since I MITM that call. I think it's also a tough call to widen the surface area of `CDP()` since it already has numerous ways to connect Chrome. I'll give it some thought and maybe raise a RFC PR

**Comment by joelgriffith** [comment]
Going to close this since it's been a while :)

**Comment by cyrus-and** [comment]
Please see #395 thread to discuss a possible solution.
