### ISSUE TITLE
Do the various Domain events and APIs create a new connection ? or use the existing connection of the client.

### ISSUE THREAD

**Issue by sravani93** [cyrus-and/chrome-remote-interface#302]
Component | Version
-- | --
Operating system | Debian GNU/Linux buster/sid
Node.js | v8.4.0
Chrome/Chromium/... | 61.0.3163.91
chrome-remote-interface | 0.23.3

Is Chrome running in a container? NO
Chrome instance(Headless) is running on port 9222.

We are running close to 75 tabs in parallel .
The "dmesg -w" gives the following output:
"request_sock_TCP: Possible SYN flooding on port 9222. Sending cookies. Check SNMP counters."

Our application uses a client connection to each tab , to obtain access to the various domains(CSS,ANIMATION,PAGE etc) .
And makes use of various APIs and Events of these domains. 

Some examples : 

await Page.captureScreenshot();
await CSS.createStyleSheet();
await Network.enable();
await Runtime.enable();
await Animation.enable();
await Emulation.setDeviceMetricsOverride();
await Emulation.setVisibleSize();

My question is : Do these calls create additional connections ? or use the existing client connection ? If its the former , It could possibly be causing the SYN flooding.

**Comment by cyrus-and** [comment]
> Do these calls create additional connections ? or use the existing client connection ?

Nope, they just send data over a WebSocket (there is one WebSocket per target).

But if your application spawns n tabs in parallel you'll have about n * 2 TCP connections (one to possibly fetch the protocol and the other is the actual WebSocket connection). The former is a short-lived connection though.

Also see #281 where many tabs are closed all at once. In particular this:

> The CDP.Close() function always causes a new TCP connection, but AFAIK this is not enough to trigger a "possible SYN flooding" message, this check should be about the queue of connections for which a SYN is received, a SYN+ACK is sent but an ACK is not yet received, a regular TCP connection stays in this state for very little time thus making it hard to reach the maximum. I suspect that there are other things going on.

Still I don't understand how is it possible that ~100 simultaneous (legit) TCP connections cause a "possible SYN flooding" message.

If you could come up with a minimal example that reproduces this behavior that would be very useful.

**Comment by cyrus-and** [comment]
Alright, so I write program to reproduce the SYN flooding issue:

```js
const CDP = require('chrome-remote-interface');
const http = require('http');

const PORT = 12345;
const DELAY = 1000;
const N = 100;

async function load(i) {
    console.log(`-- pre ${i}`);
    const target = await CDP.New();
    const {id} = target;
    const client = await CDP({target});
    const {Page} = client;
    await Page.enable();
    await Promise.all([
        Page.navigate({url: `http://localhost:${PORT}/${i}`}),
        Page.loadEventFired()]);
    console.log(`-- loaded ${i}`);
    await CDP.Close({id});
    console.log(`-- post ${i}`);
}

async function run(n) {
    const input = Array.from(Array(n).keys());
    await Promise.all(input.map(load));
}

const server = http.createServer((request, response) => {
    setTimeout(() => {
        response.end('hello');
    }, DELAY);
});

server.listen(PORT, async () => {
    console.log(`-- listening`);
    await run(N);
    server.close();
    console.log(`-- done`);
});
```

My system has `net.ipv4.tcp_max_syn_backlog` set to 256. The above script run without warnings for N = 100 on my modest machine. With N = 200 I see the warning and that seems legit because for each tab we have (for port 9222):

1. TCP connection for tab creation;
2. TCP connection for `/json/protocol`;
3. TCP connection for the WebSocket;
4. 1 second delay;
5. TCP connection for tab closing.

Now this is a quite unfortunate situation where *ideally* all the instances of 1,2,3 and all the instances of 5 are executed *simultaneously*. (Of course due to limited resources, a single request may require far more than ~1sec, so everything will be happily interleaved.) It's thus perfectly normal that the system cannot keep up with the requested workload and in particular that it may happen that, in a given moment, the number of new TCP connections for which a SYN is received, a SYN+ACK is sent but an ACK is not yet received grows above 256 thus causing the kernel to send out cookies and showing that warning.

Possible solutions involve:
1. get a faster machine / split the load on more nodes;
2. if the behavior is triggered by a mass operation, e.g., close *all* the tabs, try to pick a small number, say n = 20, and run the operation in batches of n element at a time;
3. if you machine can easily keep up with the load anyway (or it's enough for your use case) you can simply raise the limit, for example:

       sysctl net.ipv4.tcp_max_syn_backlog=1024

**Comment by sravani93** [comment]
Hi @cyrus-and , 

Thank you for the elaborate response . Will follow the solutions advised .
I have a few questions though : 
 
- Could you please elaborate on what you mean by - "TCP connection for /json/protocol" .
- "TCP connection for tab creation" is a short lived connection right ? 
- "const client = await CDP({target});" forms the "TCP connection for the WebSocket;" ?

**Comment by cyrus-and** [comment]
> Could you please elaborate on what you mean by - "TCP connection for /json/protocol" .

Every time a new connection is made (via `CDP()`) the actual protocol, which may be different across different versions of Chrome, is [fetched][1] via the `/json/protocol` HTTP endpoint. It's basically an invocation of [`CDP.Protocol()`][2]. Of course if you provide your own version of the protocol (via the `protocol` option, this step is skipped).

[1]: https://github.com/cyrus-and/chrome-remote-interface/blob/3d9ef5c648f8ee9d10ea2221d4b86101264cac50/lib/chrome.js#L167-L182
[2]: https://github.com/cyrus-and/chrome-remote-interface#cdpprotocoloptions-callback

> "TCP connection for tab creation" is a short lived connection right ?

I mean that a connection is established for that purpose but it's not persistent, that is, it's immediately closed. Actually, points 1, 2 and 5 are all short-lived connections, not that it would make any difference in the context of SYN flooding, but it's nevertheless important to understand what happens.

> "const client = await CDP({target});" forms the "TCP connection for the WebSocket;" ?

Yes, first the protocol is fetched, then the connection is made, see [here][3].

[3]: https://github.com/cyrus-and/chrome-remote-interface/blob/3d9ef5c648f8ee9d10ea2221d4b86101264cac50/lib/chrome.js#L138-L164

**Comment by sravani93** [comment]
(Y) thanks a lot.

**Comment by cyrus-and** [comment]
You're welcome!

Just a question, is this related to #281? I mean the OP there seems to work for the same company as yours and part of the issue text is the same, I was wondering if you two were working on the **same** project. If that's not the case you may want to sync with him.

**Comment by sravani93** [comment]
Yes , We're working together and in sync regarding this. :)
