### ISSUE TITLE
Pull /json/protocol in non-headless?

### ISSUE THREAD

**Issue by paulirish** [cyrus-and/chrome-remote-interface#305]
I was expecting `remote:true` to pull `/json/protocol` when using a recent Chrome that's not headless.

But it appears that a UA sniff for headless is required to get that to work. Perhaps it should just be checking against chrome version only?

**Comment by paulirish** [comment]
Ah I see you completely changed this in master recently. :)

Perhaps you now default to remote and let the user force to `local` themselves?

**Comment by cyrus-and** [comment]
Yep, it's `remote` by default since 1457e73c4893a23241406d9a174930471da2d30c. Users can alter this behavior by setting `local: true` or by passing a custom `protocol`.

I also recently removed the UA check (d4c110316016a66d0ce1f19ab0954f4a5f7da135) since in all the cases the protocol was fetched from `/json/protocol` and the check merely ruled out unknown implementation, e.g., Opera, CEF, etc. #300

**Comment by paulirish** [comment]
awesome. that's great. :)
