### ISSUE TITLE
Cancel running download

### ISSUE THREAD

**Issue by hgfdd** [cyrus-and/chrome-remote-interface#367]
Hello!

I use your library to load different urls and i need to determine urls which loads different files and stop their loading. So i have the following issue. When i load url, such as (https://browser.yandex.ru/download/?_rdr=com&banerid=6302000000%3A5bccb768f2c85d00172c7201&utm_referrer=https%253A%252F%252Fwww.google.ru%252F&zih=1&beta=1&os=linux&x64=1&package=deb&full=1) with the parameter 'allow', i see that it's loading something and close client and tab. But if open iftop i see that it still loads and several workers overload network.

When i use parameter 'deny' it hangs until my timeout. So what the proper way to handle such urls?

To reproduce the problem you can use basic example with my example url:
https://github.com/cyrus-and/chrome-remote-interface/wiki/Async-await-example

Thanks in advance!

| Component | Version
|-|-
| Operating system	  	 	| Centos 7
| Node.js					| 7.7.4
| Chrome/Chromium/...		| 68
| chrome-remote-interface	| 0.25.5

Is Chrome running in a container? YES

**Comment by cyrus-and** [comment]
Hi!

What are the `deny` and `allow` parameters? Are you referring to [`Page.setDownloadBehavior`][1]?

> i see that it's loading something

How you do that?

Anyway, I'm afraid you're out of luck here, the API doesn't provide a way to interact with the downloads AFAIK.

A couple of random thoughts:
- instead of closing the tab kill the whole Chrome instance, it should be easy with [chrome-launcher][2];
- develop a Chrome extension that *somehow* cancels the download for you using the [`chrome.downloads`][3].

It's hard to tell without knowing the full use case.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDownloadBehavior
[2]: https://github.com/GoogleChrome/chrome-launcher
[3]: https://developer.chrome.com/extensions/downloads
