### ISSUE TITLE
How to run successfully window.onload function on page?

### ISSUE THREAD

**Issue by n3pixowe** [cyrus-and/chrome-remote-interface#376]
Hello, I try to inejct a little eventListener javascript into the target website. I want to return a result or console log when the window is loaded fully. This function is not working, how can I do this?
```
await Runtime.evaluate({
    expression: `
        window.onload = () => console.log('deneme');
    `
});
```

**Comment by cyrus-and** [comment]
Take a look at #169.

**Comment by n3pixowe** [comment]
Thanks so much. But my window.onload function is not working with this piece of code.

```
await Runtime.evaluate({
    expression: `new Promise((fulfill, reject) => {
        window.onload = () => {
            alert('rendered');
            fulfill();
        });
    })`,
    awaitPromise: true
});
```
It misses my onload function. How can exactly detect the Page is fully loaded all the contents?

![untitled](https://user-images.githubusercontent.com/37420200/48906395-605b9880-ee75-11e8-8a66-e725a8be22c1.png)

**Comment by cyrus-and** [comment]
If your only goal is to listen for that event you can use [`Page.loadEventFired`][1] or [`Page.domContentEventFired`][2].

The above approach is not working because (I guess) the `onload` event is already fired when the script is injected.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-loadEventFired
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-domContentEventFired
