### ISSUE TITLE
Page.loadEventFired not triggered

### ISSUE THREAD

**Issue by M4rk9696** [cyrus-and/chrome-remote-interface#399]
This script freezes after `Page 1 loaded`. 

Possibly related to #324, script was created from POC given in that issue

```js
const CDP = require('chrome-remote-interface');

async function wait(duration) {
  process.stdout.write('Waiting ' + duration + ' ms ')
  await new Promise(resolve => setTimeout(resolve, duration))
  console.log('- done!')
}

CDP(async (client) => {
  const {Page, Debugger, Runtime, Console, Network, Log} = client;

  try {
    await Page.enable();
    await Runtime.enable();
    await Log.enable();
    await Network.enable();

    await Page.navigate({url: 'https://earth.nullschool.net/zh-cn/#2019/05/01/0600Z/wind/surface/level/overlay=temp/orthographic=-247.49,35.34,1092/loc=114.340,30.651'});
    await Page.loadEventFired();
    console.log("Page 1 loaded");
    await wait(1000);

    await Page.navigate({url: 'https://earth.nullschool.net/zh-cn/#2019/05/01/0600Z/wind/surface/level/overlay=temp/orthographic=-247.49,35.34,1092/loc=114.340,30.651'});
    await Page.loadEventFired();
    console.log("Page 2 loaded");
    await wait(1000)
  } catch (err) {
    console.error(err);
  } finally {
    client.close();
  }
}).on('error', (err) => {
  console.error(err);
});
```

| Component | Version
|-|-
| Operating system	  	 	| OSx 10.14.5 
| Node.js					| v8.16.0
| Chromium		| Version 76.0.3803.0 (Developer Build) (64-bit)
| chrome-remote-interface	| 0.27.1

Is Chrome running in a container?  NO

**Comment by cyrus-and** [comment]
The reason is this: [DevTools: introduce Page.navigatedWithinDocument event][1].

I figured out by adding the following code to see what events were passing through the WebSocket:

```js
client.on('event', (message) => {
    console.log(message);
});
```

Without knowing more, a trivial solution would be:

```js
await Promise.race([
    Page.loadEventFired(),
    Page.navigatedWithinDocument()
]);
```

Not the most beautiful piece of code... but I'm afraid we can't do any better with what Chrome is giving us. You can always wrap it in a function.

[1]: https://chromium-review.googlesource.com/c/chromium/src/+/999115/
