### ISSUE TITLE
What is "params"?

### ISSUE THREAD

**Issue by vbisbest** [cyrus-and/chrome-remote-interface#427]
I dont understad the variable params.  The code snippets posted in the readme do not work in vscode because:

params implicitly has any type.  

See screenshot.

![Screen Shot 2020-09-09 at 11 53 29 AM](https://user-images.githubusercontent.com/3143293/92622608-3b772600-f293-11ea-9544-3fb60db348df.png)

**Comment by cyrus-and** [comment]
It does work on my end, you must be doing something fancy with TypeScript (which is not supported)?

`params` is a generic object, whose properties are according to the method, in your case is [`Network.requestWillBeSent`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent).

**Comment by matjaeck** [comment]
This is likely because of the build-in TS/JS linting in vscode. You can disable TS validation in the (user/workspace) settings (this should be enough for this issue) or disable all the built-in linting and use plugins like ESLint in JS workspaces or TSLint is TS workspaces. Unfortunately it's a mess and I can't check my editor settings right now, maybe you find some helpful answers in 
- https://stackoverflow.com/questions/42632215/how-to-disable-typescript-warnings-in-vscode
- https://stackoverflow.com/questions/50823743/disable-tslint-in-vscode.

Not too precise, I kbow, hope it helps a bit though.

**Comment by cyrus-and** [comment]
@matjaeck thanks for chiming in, I'm no a vscode user but how come TypeScript errors pop up in a pure JavasScript code?

FWIW opening the README example in a vanilla vscode setup works as expected.

**Comment by matjaeck** [comment]
@cyrus-and I can neither reproduce the specific error, but the `ts(7006)` label shows that it comes from the built-in `vscode.typescript-language-features` extension (one can find it in the extension tab when searching for `@builtin TypeScript and JavaScript Language Features`).

> The TypeScript extension powers our javascript intellisense which is why you see [TS] in your js file. That only indicates what extension is providing that error

[Microsoft/vscode/#54691](https://github.com/Microsoft/vscode/issues/54691#issuecomment-406440968)

Users have also reported a while ago that they see random errors ([Microsoft/vscode/#54261](https://github.com/microsoft/vscode/issues/54261)). I don't know if those reports have ever been or are still valid, but I can reproduce a similar warning, although having typescript validation disabled in user (topright window) and workspace setting (bottom right, no overrides).
![Bildschirmfoto von 2020-09-10 01-02-48](https://user-images.githubusercontent.com/59416324/92665841-dc9fc400-f307-11ea-8ae1-75c142a2ed17.png)

The only way I know to fix these warnings and potentially errors too is to set `"javascript.validate.enable": false` and setup own tooling with for example ESLint. It's not nessecary on my system because I see only these unobtrusive mouse-over-suggestions.

**Comment by vbisbest** [comment]
Thank you @matjaeck, this was the issue.  However, I was able to use "noImplicitAny": false to fix this.

**Comment by westy92** [comment]
You can now use unofficial typings here: https://www.npmjs.com/package/@types/chrome-remote-interface

Related: https://github.com/cyrus-and/chrome-remote-interface/issues/112
