### ISSUE TITLE
Auto select "Save as" prompt without user Interaction

### ISSUE THREAD

**Issue by AlexanderTAmos** [cyrus-and/chrome-remote-interface#461]
I am building a project which uses `chrome-remote-interface` as its core component. When I click a button on a website using `Input.dispatchMouseEvent`, A prompt `Save As` (https://imgur.com/a/igVndsb) opens.

How can I avoid `Save As` prompt and **auto save to any location** ??

**Comment by cyrus-and** [comment]
Please take a look at the following example that downloads the file and save it to `/tmp/`:

```js
const CDP = require('chrome-remote-interface');

(async () => {
    const client = await CDP();
    client.Page.downloadWillBegin(({guid, suggestedFilename}) => {
        console.log(`[${guid}] downloading ${suggestedFilename}`);
    });
    client.Page.downloadProgress(({guid, state}) => {
        if (state === 'completed') {
            console.log(`[${guid}] done`);
            client.close();
        }
    });
    await client.Page.enable();
    await client.Page.setDownloadBehavior({
        behavior: 'allow',
        downloadPath: '/tmp/'
    });
    await client.Page.navigate({url: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Google_Chrome_icon_%28September_2014%29.svg?download'});
})();
```

See this [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1204880) as for why I'm using the deprecated [`Page.downloadProgress`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-downloadProgress) etc. instead of [`Browser.downloadProgress`](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#event-downloadProgress) etc.
