### ISSUE TITLE
errors from Runtime.evaluate({expression: ''}) are passed unconventionally

### ISSUE THREAD

**Issue by crediblenotand** [cyrus-and/chrome-remote-interface#51]
inspired from https://github.com/cyrus-and/chrome-har-capturer/blob/a62406a5a32bb6a4ef0b5fbcc8e64fd6dba78552/lib/client.js#L82

the following:

```javascript
chromeInstance.Runtime.evaluate({expression: CLEANUP_SCRIPT})
```

will pass the following error to the 2nd argument of the callback or to a `.then`

```javascript
{ result: 
   { type: 'object',
     subtype: 'error',
     className: 'ReferenceError',
     description: 'ReferenceError: chrome is not defined\n    at <anonymous>:1:1',
     objectId: '{"injectedScriptId":1,"id":1}' },
  exceptionDetails: 
   { exceptionId: 1,
     text: 'Uncaught',
     lineNumber: 0,
     columnNumber: 0,
     scriptId: '30',
     exception: 
      { type: 'object',
        subtype: 'error',
        className: 'ReferenceError',
        description: 'ReferenceError: chrome is not defined\n    at <anonymous>:1:1',
        objectId: '{"injectedScriptId":1,"id":2}' } } } 
```

**Comment by cyrus-and** [comment]
That happens because JavaScript errors of the [Runtime](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#method-evaluate) domain are not errors of the protocol so Chrome sets the `error` argument of the [callback](https://github.com/cyrus-and/chrome-remote-interface#chromesendmethod-params-callback) to `false` and returns the error details in `response`.
