### ISSUE TITLE
TS typings do not support the `sessionId` parameter.

### ISSUE THREAD

**Issue by AlexKamaev** [cyrus-and/chrome-remote-interface#534]
The following methods can be used with the `sessionId` parameter:
- Fetch.enable
- Fetch.continueRequest
- Fetch.continueResponse

However, currently, TypeScript typings do not support this parameter. Therefore, we need to add a `tsignore` declaration to ignore the error.

**Comment by kazarmy** [comment]
> Therefore, we need to add a `tsignore` declaration to ignore the error.

@AlexKamaev If the `tsignore` is bothersome, using the `send()` method should work e.g.:

```ts
this._client.send('Fetch.enable', { patterns: ALL_REQUESTS_DATA }, event.sessionId);
```

A more general fix would probably have to wait until the weekend.

> PS @westy92 @kazarmy every time someone opens an issue about typings I'm pinging you guys

@cyrus-and Well the current ping rate is well within tolerable levels so I have no issues with you pinging me, and anyhow this does appear to be a valid issue.

**Comment by kazarmy** [comment]
I've merged [a fix](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65583).

**Comment by kazarmy** [comment]
For [this @ts-ignore](https://github.com/DevExpress/testcafe/blob/3c1f51024b16b253942e0373bcd3adb79f384217/src/native-automation/request-pipeline/index.ts#L394-L395):

![_client Fetch on](https://github.com/cyrus-and/chrome-remote-interface/assets/12002672/ef812d17-c0c9-4169-8a85-6f85a8ccd046)

use the following for type-checking:

```ts
this._client.on('Fetch.requestPaused', async (event: RequestPausedEvent, sessionId: SessionId) => {
```

I've tried to add typings support for the former but apparently TypeScript is not there yet (the high Problems count is mostly due to ESLint not finding some rule definitions):

![on-error](https://github.com/cyrus-and/chrome-remote-interface/assets/12002672/15ca2771-588f-42a5-8834-d1a2e06f566d)

So close yet so far.
