### ISSUE TITLE
Notifier not accessible with Promise API?

### ISSUE THREAD

**Issue by inca** [cyrus-and/chrome-remote-interface#72]
By following [this line](https://github.com/cyrus-and/chrome-remote-interface/blob/master/index.js#L27) I conclude that there is no public way to subscribe to `disconnect` or `error` events when using Promise API (please correct me if I'm wrong).

Example:

```es6
CDP(/*...*/).then(client => {
  client.on('disconnect', onDisconnect); // does not fire
  client._notifier.on('disconnect', onDisconnect); // fires, but _private
});
```

**Comment by cyrus-and** [comment]
You're right. Both `disconnect` and `error` events basically mean: your connection has been closed. If you really want to distinguish (and use the promises API) you can simply check the error message.

In your example the first one does not fire since the client does not represent the notifier, which, as you say, it's not accessible via the promises API.

**Comment by inca** [comment]
@cyrus-and Thanks you for very quick response! I was going to implement something like `reconnect` after the connection is lost (e.g. due to DevTools open), so I initially assumed that Promise/callback API are mirrors of each other, but apparently this isn't true. Now, since accessing private `_notifier` doesn't sound good, I guess I need to stick with callback-based API.

Thanks for clarifying!

**Comment by cyrus-and** [comment]
They are not 100% equivalent because promises only have two states. I certainly could have exposed the notifier upon fulfillment, but it would have been too cumbersome to use.

FWIW I have no plan to drop/change the `_notifier` attribute anytime soon, if you really need to use that...
