### ISSUE TITLE
Empty "params" object

### ISSUE THREAD

**Issue by Janpot** [cyrus-and/chrome-remote-interface#77]
Some devtools targets don't accept messages without `"params"` property.
see: https://bugs.chromium.org/p/chromium/issues/detail?id=679350
This will be fixed in a future version but maybe it could be an idea to always send a `"params"` property with `chrome-remote-interface` anyway?

**Comment by cyrus-and** [comment]
AFAIK there's no formal specification describing the format of the messages, that states whether the `params` can be omitted or not. But the fix for that issue says:

> Some DevTools clients omit the "params" object for commands that don't take any parameters. Be less strict about requiring it to support these clients.

Suggesting that the *strict* behavior is to always include the `params` field in messages.

(/note to self)

So yes I think it's a good idea. Thanks for pointing this out!
